skip_local_validator = true

[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_rwa_fyp = "APGJ8oXi2fbFsMXkiRJv846X7BoJpXZDmZXJRgXHGUmf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
