skip_local_validator = true

[toolchain]
anchor_version = "1.2.0"


[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_rwa_fyp = "12ET83PFMoQeCdRwhTnbSKN9rHWSEafVeVLoJA2JYFuP"

[programs.devnet]
solana_rwa_fyp = "12ET83PFMoQeCdRwhTnbSKN9rHWSEafVeVLoJA2JYFuP"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
